server:
  port: 8080 #应用的端口
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: /home/tmp
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #mysql数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CloudDrive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #redis数据库
  data:
    redis:
      host: 124.220.152.5
      port: 6379
      password: 777888love@#
      database: 0
      timeout: 2000
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
#jimmer框架相关配置
jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  database-validation-mode: ERROR
# springdoc-openapi项目配置,访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - io.github.mellivorines.clouddriveweb.dao.input
        - io.github.mellivorines.clouddriveweb.dao.entity
        - io.github.mellivorines.clouddriveweb.controller
# knife4j的增强配置，不需要增强可以不配,访问地址：http://127.0.0.1:8080/doc.html
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: "实体类"
#项目相关自定义配置
CloudDrive:
    file:
      path: D://CloudDrive

