server:
  port: 8080 #应用的端口
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #mysql数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CloudDrive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #redis数据库
  data:
    redis:
      host: 124.220.152.5
      port: 6379
      password: 777888love@#
      database: 0
      timeout: 2000
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
#jimmer框架相关配置
jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  database-validation-mode: ERROR
# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
CloudDrive:
  jwt:
    header: Authorization
    expire: 604800 # 7天，s为单位
    secret: abcdefghabcdefghabcdefghabcdefgh

